### ISSUE TITLE
行内块元素水平间隙问题

### ISSUE THREAD

**Issue by LeeRayno** [LeeRayno/H5#1]
当行内元素之间有 “回车”、“tab”、“空格” 时就会出现间隙。

给`.container`设置 `font-size: 0;`即可

html
``` html
<div class="container">
  <span>1</>
  <span>2</>
  <span>3</>
  <span>4</>
  <span>5</>
</div>
```

scss
``` scss
div {
  width: 500px;
  height: 50px;
  margin: 0 auto;
  font-size: 0;
  font-family: -apple-system;
  
  span {
    display: inline-block;
    width: 50px;
    height: 50px;
    line-height: 50px;
    text-align: center;
    background: #333;
    color: #fff;
    font-size: 16px;
  }
}

```
